# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"          # .next is correct for the Next.js plugin

[functions]
  node_bundler = "esbuild"

# Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Auto-generates /sitemap.xml
[[plugins]]
  package = "netlify-plugin-sitemap"

  [plugins.inputs]
    baseUrl = "https://abseducationalsolution.com"  # ← your canonical domain