# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"          # .next is correct for the Next.js plugin

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ► NEW – Netlify Sitemap plugin (auto-generates /sitemap.xml)
[[plugins]]
  package = "netlify-plugin-sitemap"

  [plugins.inputs]
    baseUrl = "https://abseducationalsolution.com"  # ← your canonical domain
