# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

# ── plugins ──────────────────────────────────────────
# Next.js adapter (no inputs allowed)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Sitemap generator  ✅ correct package name
[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    # canonical site URL used in the <loc> tags
    baseUrl   = "https://abseducationalsolution.com"
    # (optional) where the generated sitemap file goes
    sitemapPath = "sitemap.xml"     # default
